run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
